apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana-config
  namespace: logging-od
  labels:
    app: logging-elastic-od-1.6.0
data:
  kibana.yml: |-
   ---
   elasticsearch.requestTimeout: 360000
   logging.verbose: false
   server.host: "0"
   server.name: kibana