apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: elastic-curator
  namespace: logging-od
spec:
  schedule: 1 0 * * * #"*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: curator
            image: untergeek/curator:5.7.6
            args:
            - --config
            - /etc/config/config.yml
            - /etc/config/action_file.yml
            volumeMounts:
              - name: config-volume
                mountPath: /etc/config
          volumes:
            - name: config-volume
              configMap:
                name: curator-config
          restartPolicy: OnFailure
