apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: logging-elastic-od-1.6.0
    role: data
  name: elastic-data
  namespace: logging-od
spec:
  serviceName: elastic-data
  replicas: 3
  selector:
    matchLabels:
      app: logging-elastic-od-1.6.0
      role: data
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: logging-elastic-od-1.6.0
        role: data
      annotations:
        
    spec:      
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - logging-elastic-od-1.6.0
                - key: role
                  operator: In
                  values:
                  - data
              topologyKey: kubernetes.io/hostname
      initContainers:
      - name: init-sysctl
        image: busybox:1.27.2
        command:
        - sysctl
        - -w
        - vm.max_map_count=262144
        securityContext:
          privileged: true
      - name: fixmount
        command: [ 'sh', '-c', 'chown -R 1000:1000 /usr/share/elasticsearch/data' ]
        image: busybox:1.27.2
        volumeMounts:
          - mountPath: /usr/share/elasticsearch/data
            name: data
            subPath: 
      serviceAccountName: logging-elastic
      containers:
      - name: elasticsearch
        env:
        - name: cluster.name
          value: elasticsearch-od
        - name: node.master
          value: "false"
        - name: node.ingest
          value: "false"
        - name: network.host
          value: "0.0.0.0"
        - name: node.name
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: discovery.seed_hosts
          value: "elastic-master"
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: node.data
          value: "true"
        - name: PROCESSORS
          valueFrom:
            resourceFieldRef:
              resource: limits.cpu
        - name: ES_JAVA_OPTS
          value: -Xms2048m -Xmx2048m
        # Official Image from Open Distro Team
        image: amazon/opendistro-for-elasticsearch:1.6.0
        imagePullPolicy: "Always"
        # only publish the transport port
        ports:
        - containerPort: 9300
          name: transport
        resources:
          limits:
            cpu: 2000m
            memory: 6Gi
          requests:
            cpu: 1000m
            memory: 4Gi            
        livenessProbe:
          initialDelaySeconds: 60
          periodSeconds: 10
          tcpSocket:
            port: transport
          
        volumeMounts:
        - mountPath: /usr/share/elasticsearch/data
          name: data
          subPath: 
        - mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
          name: config
          subPath: elasticsearch.yml
        - mountPath: /usr/share/elasticsearch/config/log4j2.properties
          name: config
          subPath: log4j2.properties

      volumes:
      - name: config
        secret:
          secretName: elastic-config
  volumeClaimTemplates:
  - metadata:
      name: data
      annotations:
         volume.beta.kubernetes.io/storage-class: "managed-premium"
    spec:
      accessModes:
        - "ReadWriteOnce"
      storageClassName: managed-premium
      resources:
        requests:
          storage: "30Gi"
