apiVersion: v1
kind: Service
metadata:
  labels:
    app: logging-elastic-od-1.6.0
    role: data
  name: elastic-data
  namespace: logging-od
spec:
  ports:
  - port: 9300
    name: transport
  - port: 9200
    name: http
  - port: 9600
    name: metrics
  clusterIP: None
  selector:
    role: data
