{{ if eq .Values.allow.kibanaEnable true }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: logging-ingress
  namespace: {{.Values.namespace}}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: {{.Values.env.oauth.nginxAuthSecretName}}
    ngnix.ingress.kubernetes.io/auth-realm: "Authentication Required - {{.Values.env.oauth.envName}}"   
spec:
  tls:
    - hosts:
      - {{.Values.env.oauth.hostName}}
      secretName: {{.Values.env.oauth.ingressSecretName}}
  rules:
  - host: {{.Values.env.oauth.hostName}}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{.Values.env.kibana.serviceName}}
          servicePort: 5601
{{ end }}