{{ if eq .Values.allow.kibanaEnable true }}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    app: logging-elastic-od-1.6.0
  name: {{.Values.env.configFiles.rbacKibana.roleBindingName}}
roleRef:
  kind: Role
  name:  {{.Values.env.configFiles.rbacKibana.roleName}}
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: {{.Values.env.configFiles.rbacKibana.serviceAccountName}}
  namespace: {{.Values.namespace}}

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: {{.Values.env.configFiles.rbacKibana.roleName}}
  namespace: {{.Values.namespace}}
  labels:
    app: logging-elastic-od-1.6.0
rules:
- apiGroups: ['extensions']
  resources: ['podsecuritypolicies']
  verbs:     ['use']
  resourceNames:
  - {{.Values.env.configFiles.rbacElasticSearch.podSecurityPolicyName}}

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{.Values.env.configFiles.rbacKibana.serviceAccountName}}
  namespace: {{.Values.namespace}}
  labels:
    app: logging-elastic-od-1.6.0
{{ end }}