{{ if eq .Values.allow.fluentdEnable true }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.env.configFiles.rbacfluentd.serviceAccountName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: fluentd
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.env.configFiles.rbacfluentd.clusterRoleName }}
  labels:
    app: fluentd
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - namespaces
  verbs:
  - get
  - list
  - watch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.env.configFiles.rbacfluentd.clusterRoleBindingName }}
roleRef:
  kind: ClusterRole
  name: {{ .Values.env.configFiles.rbacfluentd.clusterRoleName }}
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: {{ .Values.env.configFiles.rbacfluentd.serviceAccountName }}
  namespace: {{ .Values.namespace }}
{{ end }}