{{ if eq .Values.allow.elasticsearchEnable true }}

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    app: logging-elastic-od-1.6.0
  name: {{.Values.env.configFiles.rbacElasticSearch.roleBindingName}}
  namespace: {{.Values.namespace}}
roleRef:
  kind: Role
  name: {{.Values.env.configFiles.rbacElasticSearch.roleName}}
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: {{.Values.env.configFiles.rbacElasticSearch.serviceAccountName}}
  namespace: {{.Values.namespace}}
---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: {{.Values.env.configFiles.rbacElasticSearch.roleName}}
  namespace: {{.Values.namespace}}
  labels:
    app: logging-elastic-od-1.6.0
rules:
- apiGroups: ['extensions']
  resources: ['podsecuritypolicies']
  verbs:     ['use']
  resourceNames:
  - logging-elastic

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{.Values.env.configFiles.rbacElasticSearch.serviceAccountName}}
  namespace: {{.Values.namespace}}
  labels:
    app: logging-elastic-od-1.6.0
{{ end }}
