{{ if eq .Values.allow.fluentdEnable true }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Values.env.fluentd.name }}
  namespace: {{ .Values.namespace }}
  labels:
    k8s-app: fluentd-logging
    version: v1
spec:
  selector:
    matchLabels:
      k8s-app: fluentd-logging
      version: v1
  template:
    metadata:
      labels:
        k8s-app: fluentd-logging
        version: v1
    spec:
      serviceAccountName: {{ .Values.env.configFiles.rbacfluentd.serviceAccountName }}                     
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: fluentd
        image: {{.Values.fluentd.imageName}}
        env:
          - name:  FLUENT_ELASTICSEARCH_HOST
            value: {{ .Values.env.fluentd.config.elasticsearchClient.host | quote }}
          - name:  FLUENT_ELASTICSEARCH_PORT
            value: {{ .Values.env.fluentd.config.elasticsearchClient.port | quote }}
          - name: FLUENT_ELASTICSEARCH_SCHEME
            value: {{ .Values.env.fluentd.config.elasticsearchClient.scheme | quote }}
          - name: FLUENT_ELASTICSEARCH_RECONNECT_ON_ERROR
            value: "true"                                                  
          - name: FLUENT_ELASTICSEARCH_SSL_VERIFY
            value: {{ .Values.env.fluentd.config.elasticsearchClient.sslVerify | quote }}
          - name: FLUENT_ELASTICSEARCH_CLUSTER_NAME
            value: {{ .Values.clusterName | quote }}
          - name: FLUENT_ELASTICSEARCH_BUFFER_FLUSH_THREAD_COUNT
            value: "15"
          - name: FLUENT_ELASTICSEARCH_USER
            value: {{ .Values.env.fluentd.config.elasticsearchClient.userName | quote }}
          - name: FLUENT_ELASTICSEARCH_PASSWORD
            value: {{ .Values.env.fluentd.config.elasticsearchClient.password | quote }}
            
        resources:
          limits:
            cpu: {{ .Values.env.fluentd.resources.limits.cpu }}
            memory: {{ .Values.env.fluentd.resources.limits.memory }}
          requests:
            cpu: {{ .Values.env.fluentd.resources.requests.cpu }}
            memory: {{ .Values.env.fluentd.resources.requests.memory }}
        volumeMounts:
        - name: fluentd-kubernetes-volume
          mountPath: /fluentd/etc/kubernetes.conf
          subPath: kubernetes.conf
        - name: config-fluentd
          mountPath: /fluentd/etc/fluent.conf
          subPath: fluent.conf
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
      - name: fluentd-kubernetes-volume
        configMap:
          name: {{ .Values.env.configFiles.fluentdKubernetesConf}}                      
      - name: config-fluentd
        configMap:
          name: {{ .Values.env.configFiles.fluendConf}}                     
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
{{ end }}