kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    app: logging-elastic-od-1.6.0
  name: logging-kibana
roleRef:
  kind: Role
  name: logging-kibana
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: logging-kibana
  namespace: logging-od
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: logging-kibana
  namespace: logging-od
  labels:
    app: logging-elastic-od-1.6.0
rules:
- apiGroups: ['extensions']
  resources: ['podsecuritypolicies']
  verbs:     ['use']
  resourceNames:
  - logging-elastic
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: logging-kibana
  namespace: logging-od
  labels:
    app: logging-elastic-od-1.6.0