
apiVersion: v1
kind: Service
metadata:
  labels:
    app: logging-elastic-od-1.6.0
    role: kibana
  name: logging-kibana
  namespace: logging-od
spec:
  ports:
  - name: kibana-svc
    port: 443
    targetPort: 5601
  selector:
    role: kibana
  type: ClusterIP
